name: "Docs"

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/workflows/docs.yaml"
      - "zensical.toml"
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    name: "Docs"
    if: ${{ !contains(github.event.head_commit.message, '#nodocs') }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pages: write
      id-token: write

    environment:
      name: docs
      url: ${{ steps.zensical.outputs.page_url }}

    steps:
      - name: "Zensical Action"
        id: zensical
        uses: cssnr/zensical-action@v1
        with:
          prepare: 'sed -i "s/>Zensical<\/a>/>Zensical<\/a> v${ZENSICAL_VERSION}/" zensical.toml'

      - name: "Send Notification"
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: ${{ steps.zensical.outputs.page_url }}
